<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Password_v-icon notranslate v-icon--_b815a5</name>
   <tag></tag>
   <elementGuidId>f4fb1362-9d86-42ad-8010-1f6c0d2c560d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-icon.notranslate.v-icon--link.fa.fa-eye.theme--light.primary--text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f138939f-904b-487b-bc12-28912b3ae889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55e092c9-bc3c-49b4-b5a6-1cfdddf0aa2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>append icon</value>
      <webElementGuid>35fc8efe-88c7-4541-b811-1ea21d10be20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate v-icon--link fa fa-eye theme--light primary--text</value>
      <webElementGuid>be5d3ffa-fb04-416a-9fbd-95891ec97e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid fill-height&quot;]/div[@class=&quot;layout align-center justify-center&quot;]/div[@class=&quot;flex lg4 md4 sm8 xs12&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;pl-6 pr-6 pt-2 pb-2 v-card v-card--flat v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;v-input v-input--is-label-active v-input--is-dirty v-input--is-focused theme--light v-text-field v-text-field--is-booted v-text-field--enclosed v-text-field--outlined v-text-field--placeholder primary--text&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/div[@class=&quot;v-input__append-inner&quot;]/div[@class=&quot;v-input__icon v-input__icon--append&quot;]/button[@class=&quot;v-icon notranslate v-icon--link fa fa-eye theme--light primary--text&quot;]</value>
      <webElementGuid>0658d4dc-f4c2-4082-acdc-f4da5fe71fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>3c86ede9-14f1-429b-bf88-6c12a0ee9719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div[2]/form/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>7aa59c99-629a-44ef-9cb5-e573010a56cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>abf1dc9a-5cd1-4228-8471-5d0df2856d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>68e953a3-4088-47cf-b7a2-f0b59600fd6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
