<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_input-nik</name>
   <tag></tag>
   <elementGuidId>693bf963-c073-4266-8590-c2b6d59b85d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>149178d3-c9ff-49bb-9256-e3609472cd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>07fad060-fc9d-4399-90f0-b1ec3b47cb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-nik</value>
      <webElementGuid>bfa594e8-39b4-420f-afbd-46c6f1c21d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae789677-b1dd-48ab-b8da-528cccfe288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>81d8c22f-11a1-47f1-b167-d8a6b4e576a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-nik&quot;)</value>
      <webElementGuid>6d23a86d-5173-4a24-9082-862e02aa8475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-nik']</value>
      <webElementGuid>c5dfb5b2-49a6-4268-8a16-0b357827504f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div[2]/form/div/div/div/div[2]/input</value>
      <webElementGuid>b9beaebe-b2e3-4b2a-8d09-4b1ff88c4643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5912f418-7be1-4ea2-bd37-3d4000fc9a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-nik' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>c9c85230-8541-4c55-a9ee-c76a2a5fca3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
