<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Detail PengajuanDetail WawancaraINQUIRY_52785f</name>
   <tag></tag>
   <elementGuidId>5eff146f-63d2-4285-8e5f-941291443f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-card__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>314e697c-54d1-4852-b640-6849ad75857f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-card__text</value>
      <webElementGuid>7b38c6b8-dd30-4dd4-8d5e-f874419762ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail PengajuanDetail WawancaraINQUIRY KREDIT ​Nomor Kredit Cari DETAIL PINJAMAN ​Tipe Nasabah​CIF​Nama Nasabah​Produk​Pola Angsuran​Tanggal Kredit​Tenor​Sisa Tenor​Tenor Tunggakan​Uang Pinjaman AwalRupiah​Pokok Per BulanRupiah​Sewa Modal Per BulanRupiah​AngsuranRupiah​Sisa PokokRupiah​Sisa Sewa ModalRupiah​Tunggakan PokokRupiah​Tunggakan Sewa ModalRupiah​Tunggakan AngsuranRupiahDETAIL RESTRUKTURISASI ​Persen OSL​Maksimal Tenor​Maksimal Tunda Pokok​Maksimal Perpanjangan​Uang Pinjaman BaruRupiah​Sewa Modal Per BulanRupiah SELANJUTNYA WAWANCARA ​Apakah Profesi Anda Saat Ini ?Pengusaha Mikro/wiraswasta​Pilih rincian jenis usaha yang anda jalankan saat ini ?Supplier Pakaian​Darimana Sumber Pembayaran Kredit Anda Saat Ini ?Keduanya​Digunakan untuk apakah dana yang dahulu anda peroleh dari pegadaian ?Pendidikan​Bagaimana Kondisi Barang Jaminan Kredit Anda Saat Ini ?sudah Tidak Ada lagi (dijual/hilang)​Bagaimana pengaruh virus corona terhadap usaha yang anda jalankan ?Distribusi penjualan terganggu​Apakah Jenis Usaha yang anda jalankan saat ini ?Perdagangan​Bagaimana kondisi usaha anda saat ini?Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan​Berapakah jumlah pendapatan anda per bulan sebelum terdampak?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah jumlah pendapatan anda per bulan saat ini?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah rata - rata jumlah pengeluaran anda per bulan saat ini ?Rupiah KEMBALIAJUKAN </value>
      <webElementGuid>30687fb8-53a0-415d-8d2a-73b60ccf12e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main secondary lighten-1 bg-mikro&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;v-card v-sheet v-sheet--outlined theme--light&quot;]/div[@class=&quot;v-card__text&quot;]</value>
      <webElementGuid>a6886e13-629f-4cb0-9355-2c8d819a33d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]</value>
      <webElementGuid>e047cffc-8cff-4d1b-8bdb-d065b62db5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENGAJUAN RESTRUKTURISASI'])[1]/following::div[1]</value>
      <webElementGuid>6d53bf1e-52be-4bc5-a3b4-e5f07f7a3035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan'])[2]/following::div[3]</value>
      <webElementGuid>82a762e8-a5d7-4642-9802-7e38cfdf0a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div[2]</value>
      <webElementGuid>3af3345b-0bef-4418-9d92-e89752423ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Detail PengajuanDetail WawancaraINQUIRY KREDIT ​Nomor Kredit Cari DETAIL PINJAMAN ​Tipe Nasabah​CIF​Nama Nasabah​Produk​Pola Angsuran​Tanggal Kredit​Tenor​Sisa Tenor​Tenor Tunggakan​Uang Pinjaman AwalRupiah​Pokok Per BulanRupiah​Sewa Modal Per BulanRupiah​AngsuranRupiah​Sisa PokokRupiah​Sisa Sewa ModalRupiah​Tunggakan PokokRupiah​Tunggakan Sewa ModalRupiah​Tunggakan AngsuranRupiahDETAIL RESTRUKTURISASI ​Persen OSL​Maksimal Tenor​Maksimal Tunda Pokok​Maksimal Perpanjangan​Uang Pinjaman BaruRupiah​Sewa Modal Per BulanRupiah SELANJUTNYA WAWANCARA ​Apakah Profesi Anda Saat Ini ?Pengusaha Mikro/wiraswasta​Pilih rincian jenis usaha yang anda jalankan saat ini ?Supplier Pakaian​Darimana Sumber Pembayaran Kredit Anda Saat Ini ?Keduanya​Digunakan untuk apakah dana yang dahulu anda peroleh dari pegadaian ?Pendidikan​Bagaimana Kondisi Barang Jaminan Kredit Anda Saat Ini ?sudah Tidak Ada lagi (dijual/hilang)​Bagaimana pengaruh virus corona terhadap usaha yang anda jalankan ?Distribusi penjualan terganggu​Apakah Jenis Usaha yang anda jalankan saat ini ?Perdagangan​Bagaimana kondisi usaha anda saat ini?Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan​Berapakah jumlah pendapatan anda per bulan sebelum terdampak?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah jumlah pendapatan anda per bulan saat ini?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah rata - rata jumlah pengeluaran anda per bulan saat ini ?Rupiah KEMBALIAJUKAN ' or . = 'Detail PengajuanDetail WawancaraINQUIRY KREDIT ​Nomor Kredit Cari DETAIL PINJAMAN ​Tipe Nasabah​CIF​Nama Nasabah​Produk​Pola Angsuran​Tanggal Kredit​Tenor​Sisa Tenor​Tenor Tunggakan​Uang Pinjaman AwalRupiah​Pokok Per BulanRupiah​Sewa Modal Per BulanRupiah​AngsuranRupiah​Sisa PokokRupiah​Sisa Sewa ModalRupiah​Tunggakan PokokRupiah​Tunggakan Sewa ModalRupiah​Tunggakan AngsuranRupiahDETAIL RESTRUKTURISASI ​Persen OSL​Maksimal Tenor​Maksimal Tunda Pokok​Maksimal Perpanjangan​Uang Pinjaman BaruRupiah​Sewa Modal Per BulanRupiah SELANJUTNYA WAWANCARA ​Apakah Profesi Anda Saat Ini ?Pengusaha Mikro/wiraswasta​Pilih rincian jenis usaha yang anda jalankan saat ini ?Supplier Pakaian​Darimana Sumber Pembayaran Kredit Anda Saat Ini ?Keduanya​Digunakan untuk apakah dana yang dahulu anda peroleh dari pegadaian ?Pendidikan​Bagaimana Kondisi Barang Jaminan Kredit Anda Saat Ini ?sudah Tidak Ada lagi (dijual/hilang)​Bagaimana pengaruh virus corona terhadap usaha yang anda jalankan ?Distribusi penjualan terganggu​Apakah Jenis Usaha yang anda jalankan saat ini ?Perdagangan​Bagaimana kondisi usaha anda saat ini?Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan​Berapakah jumlah pendapatan anda per bulan sebelum terdampak?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah jumlah pendapatan anda per bulan saat ini?(Seluruh pendapatan termasuk pasangan)Rupiah​Berapakah rata - rata jumlah pengeluaran anda per bulan saat ini ?Rupiah KEMBALIAJUKAN ')]</value>
      <webElementGuid>831bef6d-0a0d-45e9-8fc6-711bb0ac7c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
