<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Kredit_nomorKredit</name>
   <tag></tag>
   <elementGuidId>5fa4224c-2a2c-49b3-a467-99090fa938eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomorKredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomorKredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68febaa1-ab69-4ff5-93c5-8304a62f28fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomorKredit</value>
      <webElementGuid>9ec4f570-bc8c-4463-abf7-d3878caef43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d1c3107-1a7f-4f77-ab70-d537569d8c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomorKredit&quot;)</value>
      <webElementGuid>0cad9a24-77ce-4526-8af5-2fa021ffb650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomorKredit']</value>
      <webElementGuid>1573b62c-c989-4648-a410-2bc488f21bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1141704e-e66e-4652-b8c4-6c9b114c96df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bc3fcb1a-fd79-4e30-93a3-e0ebf213c992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nomorKredit' and @type = 'text']</value>
      <webElementGuid>e8d534a6-f11c-48ee-b7f4-3ba5688bfca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
