<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pendidikan_penggunaanDana</name>
   <tag></tag>
   <elementGuidId>92aa82c8-7e6d-4886-81b3-75048d12fd44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#penggunaanDana</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='penggunaanDana']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb18efa9-447c-41de-a06c-7a5d30888be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penggunaanDana</value>
      <webElementGuid>26cb4a51-9ce4-4809-86bc-0efb4051a9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>ffdd6609-05c4-4add-afe3-c2e7e54fb804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95a9ce27-3dbc-4845-b03c-b4bfbdefe463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9d31fbb3-a16d-49ac-8b4b-6819506fd323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8f5018df-b35a-4dbb-acf4-a28b1593338b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-493-3</value>
      <webElementGuid>b0bff1fe-e62a-4cc0-9f27-53c07482acb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penggunaanDana&quot;)</value>
      <webElementGuid>b586d973-9c96-415b-8169-904429ab6129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='penggunaanDana']</value>
      <webElementGuid>003858c4-02b9-49ba-8eb2-438368bbd2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>df8cb000-f420-445d-852a-79eebbc9794c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/div/div/div/div/div/input</value>
      <webElementGuid>7f997c3c-5afe-4e65-aca1-1813d611e693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'penggunaanDana' and @type = 'text']</value>
      <webElementGuid>45d007bb-4040-4d1d-9f40-97952775d0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
