<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sudah Tidak Ada lagi (dijualhilang)_k_705d5c</name>
   <tag></tag>
   <elementGuidId>c04b493b-6452-4c02-be73-68dffdfd4811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kondisiBarangJaminan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kondisiBarangJaminan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e4a3ba4-9d54-4ee1-8776-f2c14d2e3437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kondisiBarangJaminan</value>
      <webElementGuid>047fafe8-c46c-4314-ad1e-bd5836284eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>29f20598-77ee-4b30-8895-9c661be154e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>665c55ab-8e35-407d-8969-c20b15a81b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e191b40-0cc2-4e3e-94c2-6ff5ac82c762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91642612-c0b6-4cf4-b329-73e93c4b909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-457-2</value>
      <webElementGuid>0cb49f94-f3c7-400f-9018-919f546f0688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kondisiBarangJaminan&quot;)</value>
      <webElementGuid>45c1574a-d20b-4c17-9d73-cae3bea80bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kondisiBarangJaminan']</value>
      <webElementGuid>411e458c-6851-4e20-8838-c6496351d622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>0b1f6fe9-fe90-49de-b824-4bd09b0cd428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>85521ed7-2a54-4717-93eb-f0cbcda39e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kondisiBarangJaminan' and @type = 'text']</value>
      <webElementGuid>59617ee2-d330-4fec-b738-5c4a3452aa50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
