<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier Pakaian_rincianJenisUsaha</name>
   <tag></tag>
   <elementGuidId>88993f03-6822-43ff-991f-17f7fa08a5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rincianJenisUsaha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rincianJenisUsaha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2632ebd-a7c4-4e8a-a920-8595e5e1c386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rincianJenisUsaha</value>
      <webElementGuid>3835436e-0808-4205-bd03-c2ffdab83efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>91cb65ba-1ac9-431c-afba-a353443dcb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d286b715-94fa-4679-8ddf-0a448d604833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e97eff98-c6c5-44ab-8891-d69de2ce9b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>de51d954-bec8-4581-96fa-71f90a8412dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-472-2</value>
      <webElementGuid>8259e9ee-fb2e-4292-98fb-01e25eb0d598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rincianJenisUsaha&quot;)</value>
      <webElementGuid>e52860b1-a606-480d-9182-4b1dfee832f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rincianJenisUsaha']</value>
      <webElementGuid>beae54d5-ca28-4d50-97ca-40b2425ee430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>32d83a3f-1c09-4695-a5d8-e0a0cff3233b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>40c8132e-c2aa-427f-86ce-9800d4a17d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rincianJenisUsaha' and @type = 'text']</value>
      <webElementGuid>f508b822-74e5-4e4a-8c36-e9daf8ad3ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
