<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah jumlah pendapatan anda per _2df2ad</name>
   <tag></tag>
   <elementGuidId>7dabfdd8-3397-4a95-9e91-67a2b2951a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-426</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-426']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42fd7d39-5ac2-467d-88e1-a49ed7e8e5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-426</value>
      <webElementGuid>9b4160d1-4db7-42dc-adee-5517687b21d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7caa1062-8f24-4532-8515-53ade02ac8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-426&quot;)</value>
      <webElementGuid>1c528779-1d70-4ed5-a805-c0bc677077f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-426']</value>
      <webElementGuid>65f2efa9-4b69-47b2-8269-fc14d9e54dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>e5f76ba1-7cb3-4ae4-86d9-b118b7d92277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>213fdd58-06de-4d00-bfc5-544734990d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-426' and @type = 'text']</value>
      <webElementGuid>8e3b085c-fa33-47a2-aa9e-89abc6798422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
