<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-421</name>
   <tag></tag>
   <elementGuidId>5f68b804-1e71-4525-8596-3a39781a5c32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-421</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-421']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>788044ef-cda3-4049-8132-d2a6e7e7ca6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-421</value>
      <webElementGuid>ec27f9b3-3357-4160-a1a8-606f0fc2f777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2492c11-f157-464a-88a4-a58eb70066f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-421&quot;)</value>
      <webElementGuid>335a7590-8e75-415c-a636-436b6ef99190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-421']</value>
      <webElementGuid>fd9d8b95-28a3-40c1-8a2f-4cd98019b860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>0599ac77-94f9-4687-adb1-190b7e9a070e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>28048cac-0a98-4290-b609-a0a5db22fd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-421' and @type = 'text']</value>
      <webElementGuid>6bd2aab8-9e69-4db6-8b86-1f9713c695cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
