<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perdagangan_jenisUsaha</name>
   <tag></tag>
   <elementGuidId>f3d53455-16e8-4e33-813f-fe52d62e8043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenisUsaha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jenisUsaha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>194920cf-9ae4-4b67-a803-1fc4308e2471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenisUsaha</value>
      <webElementGuid>337df153-4f10-49a7-ba0a-a322781456f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>db462bb6-7a9d-4372-8a95-94d275a0bcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04cb61c1-6340-477a-9685-2b81e6199f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>10ed8439-36a7-4d31-bd07-12a0cf7fa170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4f527d3-a134-4790-ac0d-14011dc28a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-464-0</value>
      <webElementGuid>530b26e7-2267-45c7-8c0c-57726803e168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenisUsaha&quot;)</value>
      <webElementGuid>5b4eca67-ea3a-4928-b785-2075de61dc88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jenisUsaha']</value>
      <webElementGuid>1468295b-09e5-4aa2-8279-ce04d2358dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>420be73e-8d77-460d-931c-b364cbaf71a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>79b645bc-9fe3-4033-b8d0-fbdce0f97cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jenisUsaha' and @type = 'text']</value>
      <webElementGuid>0a6fa39f-4270-437d-8ee6-6f8604197891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
