<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah rata - rata jumlah pengelua_59ab20</name>
   <tag></tag>
   <elementGuidId>b1989937-3ecc-4fa9-8168-1ab7f58e0248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-431</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-431']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25a66733-2830-46a3-9e99-2a19b797cca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-431</value>
      <webElementGuid>94640f32-5c0b-4029-90d2-1d2bdb60b245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db181182-0bfa-4ac2-8949-367c0dfedb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-431&quot;)</value>
      <webElementGuid>65cd4499-d83e-4c0b-bcda-df5120a46ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-431']</value>
      <webElementGuid>f142eb68-d108-40de-9945-1bb18afec05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>0b9d42a8-efeb-4473-a8d1-af180dfaf451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>5dcab61c-0566-4544-b6e8-d74c2c1cfe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-431' and @type = 'text']</value>
      <webElementGuid>0c43ecfc-769f-466e-bdea-1df6824209e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
