<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Distribusi penjualan terganggu_dampakPandemi</name>
   <tag></tag>
   <elementGuidId>e6977b41-bd06-4357-a8c7-06999b0e79e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dampakPandemi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dampakPandemi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>415fec0d-81a7-44c2-9b94-837f457348d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dampakPandemi</value>
      <webElementGuid>96d0b6c7-faf0-4578-ab5f-0ab95f12ee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f6bacbe3-673f-4969-981f-b5f5088eebfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>610dbd49-ead6-417e-846b-aedc677b75ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>633588c0-b294-40e9-95a7-475ff152b49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12616222-327a-4709-989f-3e2f6208dba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-503-2</value>
      <webElementGuid>f0686365-5c4a-478f-b650-6f1a4d7f4825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dampakPandemi&quot;)</value>
      <webElementGuid>8adb8cdb-39ad-4667-9acb-1e6e6a52f81c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dampakPandemi']</value>
      <webElementGuid>a6983f2c-a120-41ec-a461-95b9088fa7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[6]/div/div/div/div/div/input</value>
      <webElementGuid>713b239e-0446-4ea1-96aa-f5174052365a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[6]/div/div/div/div/div/input</value>
      <webElementGuid>1aacf993-03c8-44af-8c42-7cb485996a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dampakPandemi' and @type = 'text']</value>
      <webElementGuid>364eceb9-8a0d-44e8-84a4-790787776093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
