<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masih berlangsung, namun menurun Ditu_8141f2</name>
   <tag></tag>
   <elementGuidId>df1f51e9-9868-44b3-af43-43cf7796302b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kondisiUsaha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kondisiUsaha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da4aeb92-1bbe-416b-a3cd-b6a9fe361a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kondisiUsaha</value>
      <webElementGuid>8e0f47ac-8aab-4a21-bd68-f4858ac44ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>47e16420-4300-4c08-b286-e65875beea84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f1899d2-9858-4e44-a849-19d32b9e249c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1808ef7a-577e-4c96-a36c-714a5928ac2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dfbd080-9ac9-48b0-ac04-bcf3c3537b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-511-1</value>
      <webElementGuid>ec8b5952-a8fa-469c-9e27-96b599ee13b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kondisiUsaha&quot;)</value>
      <webElementGuid>285a7e58-377a-446c-9b0f-6311081d51ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kondisiUsaha']</value>
      <webElementGuid>db54e65f-6528-4ce0-afdf-75ba0f811c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[8]/div/div/div/div/div/input</value>
      <webElementGuid>789d560e-983b-45d4-b76e-e5362dd82ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[8]/div/div/div/div/div/input</value>
      <webElementGuid>f47c745a-25da-49d2-8ac0-9a10906c7f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kondisiUsaha' and @type = 'text']</value>
      <webElementGuid>cb94deaf-381a-4bb8-b03f-186211d641c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
