<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keduanya_sumberPembayaranKredit</name>
   <tag></tag>
   <elementGuidId>61eb1e4b-7df3-4aca-823e-81fb09865bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sumberPembayaranKredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sumberPembayaranKredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba4d432b-34e9-41e9-8a7e-9ea05a2e5b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sumberPembayaranKredit</value>
      <webElementGuid>d7be70a5-f85c-43e5-b279-920b5b1dc0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>7381876a-0a1e-4719-a298-9413d145f728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c4eaf37-0d77-4770-bbe1-d51042ee92a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68de3ac7-455e-45d4-a13f-4a348403b75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e295bec6-baec-4e04-b6d9-686bc5780039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-450-2</value>
      <webElementGuid>dad31117-0463-4b10-bf56-5958405cd786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sumberPembayaranKredit&quot;)</value>
      <webElementGuid>805fffa3-a59b-4303-82dc-7dd0a0e61fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sumberPembayaranKredit']</value>
      <webElementGuid>f23f253b-8a56-47db-849e-ab62009b5ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>cfb99852-0752-4eef-9ed4-cc082e664e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>eb1eb5fc-c027-4e84-8db0-53793ce35c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sumberPembayaranKredit' and @type = 'text']</value>
      <webElementGuid>094e1781-297a-4f9f-b8b7-bd8e8519bdda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
