<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_input-nik</name>
   <tag></tag>
   <elementGuidId>19d1b715-79fc-48b3-a320-105f1cd0f73e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a25bd3b-cde3-41bf-9d25-51dc9994b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>79d1b092-8185-448d-9857-cc31968bf79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-nik</value>
      <webElementGuid>be8eb7ee-d0cd-4072-b02f-c574dcafef3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96ed16df-8e63-4853-baa1-07b0c89be216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>30d608ce-6f12-4274-8093-292d5be0dbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-nik&quot;)</value>
      <webElementGuid>de75da35-1d0c-4897-88a4-d3b98d722f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-nik']</value>
      <webElementGuid>a33d6b48-35ed-42e8-8f2c-c8ea6d0481cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div[2]/form/div/div/div/div[2]/input</value>
      <webElementGuid>7b8f7a60-ff11-4f7b-9a3d-f3cee8ecf2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b9130ad-0e90-455c-982b-016b66374372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-nik' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>63d14411-15a4-4ff9-bdc5-a7a7d8052dec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
