<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_input-nik</name>
   <tag></tag>
   <elementGuidId>a213bc20-d84e-43fe-9829-1ad0b5433320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>599dcc7e-f12a-4b75-9f37-1df1b2ab4b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3a46ef5f-2f9b-4c8c-b451-ca3b63ea023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-nik</value>
      <webElementGuid>c03b9a6c-cdce-4cbb-a60d-d0729b763946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba6b8643-35d8-4d99-8fb0-d27e053781d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>0af7b703-e6f9-42c0-92de-22c7ec5a7a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-nik&quot;)</value>
      <webElementGuid>3639ced3-55a4-4d6b-ac06-64e71a738aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-nik']</value>
      <webElementGuid>a65a6526-ccaf-4f24-a459-a32985281dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div[2]/form/div/div/div/div[2]/input</value>
      <webElementGuid>2fb7994d-37cb-415b-bf28-ddf79b126053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>023e8936-3b5d-4098-86a9-a1feea3725bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-nik' and @type = 'text' and @placeholder = 'Username']</value>
      <webElementGuid>d194c9dc-7992-4171-953b-ed858dc9e7fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
