<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masih berlangsung, namun menurun Ditutu_3a8758</name>
   <tag></tag>
   <elementGuidId>0303fb0b-5e72-49e9-8565-b8b3efd92080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-511-1 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-511-1']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7cda0f1-78b8-46ae-b422-e3973b3fb775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>aeddf085-263e-497c-9570-14b7af1bbaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan</value>
      <webElementGuid>757df67c-763f-4460-af56-b1f4400bf2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-511-1&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]</value>
      <webElementGuid>a503b968-3281-46c1-a3ca-4d0a26ea004c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-511-1']/div/div</value>
      <webElementGuid>88ba8281-23e4-47d9-88ba-01df0b3fe899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usaha sudah tutup sejak bulan Desember 2019'])[1]/following::div[3]</value>
      <webElementGuid>2e732d2d-8d74-4653-9ea6-105e676b39a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pasar/pelanggan menurun'])[1]/following::div[8]</value>
      <webElementGuid>47755868-7468-4489-b567-f540eab99661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangsung seperti biasa'])[1]/preceding::div[1]</value>
      <webElementGuid>ef610f59-b7f3-4220-a8ca-4369257c87fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan']/parent::*</value>
      <webElementGuid>aa2b4b0b-7e66-4eae-a658-684fa80457db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/div/div</value>
      <webElementGuid>ddfb79ab-fd03-4f09-8a45-611b00ef2f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan' or . = 'Masih berlangsung, namun menurun Ditutup sementara, ada rencana dilanjutkan')]</value>
      <webElementGuid>f0c7f68a-1c58-4e67-b160-2f3788c682a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
