<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Kredit_nomorKredit</name>
   <tag></tag>
   <elementGuidId>891fa902-9765-4c7f-88bc-91e8ad935d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomorKredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomorKredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5d732fc-41eb-4587-aa9f-96c56ae07916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomorKredit</value>
      <webElementGuid>c114cb0c-4200-49cf-87a5-e0659f5649b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5e4c9b21-9ed8-43a1-8f7c-47a15c633948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomorKredit&quot;)</value>
      <webElementGuid>1611929c-98e9-4281-a4c5-e943ac17f6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomorKredit']</value>
      <webElementGuid>3a7dff08-6565-4af0-927b-9a89180fc3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>320a155e-3f6b-4463-9d0c-b25193db2efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>18ed9789-45c9-489b-9d7c-6eca0efc6b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nomorKredit' and @type = 'number']</value>
      <webElementGuid>26f0c528-c00d-4615-8608-baa3929df7c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
