<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah jumlah pendapatan anda per _2df2ad</name>
   <tag></tag>
   <elementGuidId>ee86a5b8-cd97-4dd1-a9bd-72d88b3ec0fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-426</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-426']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b603ca96-11af-4d4d-8ea4-8d534fd27cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-426</value>
      <webElementGuid>24ac0c58-b455-4574-bde8-9c41c748706f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6275099d-c507-448d-88dd-b393b51040d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-426&quot;)</value>
      <webElementGuid>eae4f09e-d18c-4324-9408-d4b5641ac124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-426']</value>
      <webElementGuid>007f697e-bda4-45e6-b1e7-67d951d99783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>defd757e-c369-47ad-aca1-728f0e683d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>4ddc8ba7-5b07-4c94-b446-5a1e6ce1cbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-426' and @type = 'text']</value>
      <webElementGuid>c0f68a8a-5acb-4958-8f27-7fbde1d30642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
