<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah rata - rata jumlah pengelua_59ab20</name>
   <tag></tag>
   <elementGuidId>240f91d0-42a0-4d4b-8cbb-c6806ccf4ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-431</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-431']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60edfa81-7bff-457f-93ae-a78519d13f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-431</value>
      <webElementGuid>691862bc-0728-45a8-8481-9c22173c8ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0638be6-9970-4c3e-9732-de162e44d8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-431&quot;)</value>
      <webElementGuid>8fba84ed-f269-4dc9-ace2-2a38478c2e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-431']</value>
      <webElementGuid>87aa941a-d0c5-4aa2-bff7-cc22c9492632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>01299f11-3593-43ff-beec-25689830d59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>dd8ed691-c018-45e9-bbbb-b3a6f05d94bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-431' and @type = 'text']</value>
      <webElementGuid>928cd4af-8c57-4ab8-9fed-5077d3ddfbd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
