<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-421</name>
   <tag></tag>
   <elementGuidId>26313ee4-ecad-4cdb-a68e-ee6187603284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-421</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-421']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>809bfefb-ff9f-4a94-8676-32b7126b2720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-421</value>
      <webElementGuid>3d07d592-350b-43f5-93af-36e62aa8ef9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3781b8dd-06a9-43ed-99fc-2508aef2ded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-421&quot;)</value>
      <webElementGuid>7d605353-0901-41f3-861d-dd095ead882a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-421']</value>
      <webElementGuid>b8ef4c5b-c45b-4ef3-b59c-3bc80cbff3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>59534161-5bd4-4d22-8299-085d9fc9c027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/input</value>
      <webElementGuid>1b7e8422-4f6a-4340-9a56-90427d7ff2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-421' and @type = 'text']</value>
      <webElementGuid>f976a229-38bc-42de-953f-8a5ecc17e5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
