<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SELANJUTNYA</name>
   <tag></tag>
   <elementGuidId>c1b5734d-bdcb-4c00-b9ed-2bd543d14d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-sde-selanjutnya > span.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-sde-selanjutnya']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>adddb8a2-f872-42c3-b2fa-69507708368a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>b7f7a44a-5496-4447-accd-f96134dd1cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SELANJUTNYA </value>
      <webElementGuid>68373956-143b-4b41-8ed6-6a5798609237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-sde-selanjutnya&quot;)/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>d14644be-411a-4add-934f-6fa701d8b736</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-sde-selanjutnya']/span</value>
      <webElementGuid>716e5d6a-befa-4ee9-bcb3-58dbafbe9dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rupiah'])[11]/following::span[1]</value>
      <webElementGuid>429d3b04-1341-4a52-8e2f-35ed18dc6661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sewa Modal Per Bulan'])[2]/following::span[1]</value>
      <webElementGuid>ecd36125-fec6-4ddb-871c-d5be11add53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. Pegadaian'])[1]/preceding::span[3]</value>
      <webElementGuid>624f712d-f0fa-4a53-a83a-2e25e8a0c2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesalahan'])[1]/preceding::span[3]</value>
      <webElementGuid>db0eeb9f-6ad9-49e5-ad81-7f0884e1f946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>0e03a8c1-d331-4976-9b08-141600855009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' SELANJUTNYA ' or . = ' SELANJUTNYA ')]</value>
      <webElementGuid>2069a716-71fe-4693-b163-62955c3c4195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
