<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah jumlah pendapatan anda per _2df2ad</name>
   <tag></tag>
   <elementGuidId>489b80ce-6b46-48ea-8474-97af8e1ab7b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-426']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-426</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f77126c6-1f9a-4a96-af6b-309eb7657234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-426</value>
      <webElementGuid>40acd427-96dd-41ce-907d-fcb466e4ab5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bdac4bc-9b72-4164-a12c-f81dfaef40e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-426&quot;)</value>
      <webElementGuid>3a5109c3-5879-4ba0-bd15-6462f9979c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-426']</value>
      <webElementGuid>97486f0b-0e59-47e9-a4ab-000d11e61166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>1bb2c305-4c3f-47dc-9c4f-270d7e3f8f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div/input</value>
      <webElementGuid>5d4843c6-f776-40f0-8430-53bf5114bb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-426' and @type = 'text']</value>
      <webElementGuid>71499d71-70d3-46bb-8a96-a7708c8c74ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
