<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Berapakah rata - rata jumlah pengelua_59ab20</name>
   <tag></tag>
   <elementGuidId>9040345b-fd3b-4ee2-8ecb-65af2fdce3c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-431']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-431</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68d0bfb2-aa15-47ec-a598-30b7612ad487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-431</value>
      <webElementGuid>e6eec4bc-4e8c-4d58-abfb-6a20f5b24ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>800bc268-0581-4024-87ec-bd311130a9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-431&quot;)</value>
      <webElementGuid>bbb4b81f-f6de-495d-a0c8-17db5628a33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-431']</value>
      <webElementGuid>03afc71a-728f-48c4-a5f7-53ce0e73b216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>0e9438a6-05ef-4ffb-9649-e34c35eb45f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/div/input</value>
      <webElementGuid>122a6afd-265e-4dba-bc42-5ffc24ea2cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-431' and @type = 'text']</value>
      <webElementGuid>8925bd71-2ce4-402f-bcac-3604ccc33ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
