<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SELANJUTNYA</name>
   <tag></tag>
   <elementGuidId>8b48214b-4c3f-4d26-ab25-7ca44c184f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-sde-selanjutnya']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-sde-selanjutnya > span.v-btn__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4ffdf0e-637a-461e-97fe-9ac29aad9996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>e8aa788c-0da0-4ae3-bc07-f5a1d1193dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SELANJUTNYA </value>
      <webElementGuid>cd65360a-2174-46bd-b256-895b9dd4219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-sde-selanjutnya&quot;)/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>83ed8db7-507c-4dbe-9646-25b4cfb1edbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-sde-selanjutnya']/span</value>
      <webElementGuid>b7a26b43-f0e6-4c66-bd81-0784fa2bbc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rupiah'])[11]/following::span[1]</value>
      <webElementGuid>265b5785-5867-4144-8377-724251a70b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sewa Modal Per Bulan'])[2]/following::span[1]</value>
      <webElementGuid>5ebfc014-d27b-4d5e-9b3a-e682745211b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. Pegadaian'])[1]/preceding::span[3]</value>
      <webElementGuid>d7e7ce73-0b36-4c64-a405-4942875d3a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesalahan'])[1]/preceding::span[3]</value>
      <webElementGuid>a234d677-c826-4f9e-89ed-68ae155f3ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>2fa11441-85c9-40a7-a0ae-46f7be8d6a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' SELANJUTNYA ' or . = ' SELANJUTNYA ')]</value>
      <webElementGuid>668842f3-e832-4246-990f-59bfa9db3f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
