<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pengusaha Mikrowiraswasta_profesi</name>
   <tag></tag>
   <elementGuidId>d02f6ac2-2048-49a0-b943-7e67361a0330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profesi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profesi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e70b181-31c6-4a41-8203-2154a7e4b65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profesi</value>
      <webElementGuid>cf332ba0-7c7b-414b-867e-e411e49651b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>9da4aa15-d2c6-4799-bef1-7161f5fcd9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2023e68-110e-49da-b385-78a572512ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25ec53d5-2ec6-430b-9fd4-11f88c0c9df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d34eb78f-c87f-42cc-be23-8d5baff22429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>list-item-440-3</value>
      <webElementGuid>1dca3e61-907f-43ec-898a-ae3e82419173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profesi&quot;)</value>
      <webElementGuid>7003eaf7-e399-44bd-bd0b-22daea08051c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profesi']</value>
      <webElementGuid>8c6ed163-d6e7-487a-872e-71b0c86b1e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3a8f4072-761b-4251-bd7a-cc7b68348c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1feecd99-8952-48b3-a1e0-07aefecc3f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profesi' and @type = 'text']</value>
      <webElementGuid>ffe36808-9063-4c52-9096-b61c8b15c71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
