<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Kredit_nomorKredit</name>
   <tag></tag>
   <elementGuidId>06499d5f-c848-44ab-b7b6-bf0c1247771d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomorKredit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomorKredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b07c5758-5269-4619-a6fc-866d9a4c2e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomorKredit</value>
      <webElementGuid>8adea4b8-6644-407d-9b1f-645a7d5719c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>03069353-593b-4550-a0b1-3721914da5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomorKredit&quot;)</value>
      <webElementGuid>25ae94d2-d7b6-41ec-8d0e-429f1f627ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomorKredit']</value>
      <webElementGuid>18d95215-9324-4c5d-9482-0e991f41bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/main/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div[2]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>078b0eee-c13a-4600-b7a8-e3288b915c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a9991925-c997-4ae5-afc9-8d5c2fb4eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nomorKredit' and @type = 'number']</value>
      <webElementGuid>4b82f446-3f37-40fc-b09d-3faec1f96f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
