<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SELANJUTNYA</name>
   <tag></tag>
   <elementGuidId>9b7bdfae-cbb9-41c2-ad0d-15fdf42cc697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-sde-selanjutnya > span.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-sde-selanjutnya']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0744df6-6cd9-48d3-a0e9-74775ae5a075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>207ae1ba-ec09-42c9-bcd9-9709614eb765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SELANJUTNYA </value>
      <webElementGuid>11d6724f-a6cd-4dfa-8347-51dabc61efa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-sde-selanjutnya&quot;)/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>0a0aca66-88a5-4766-9647-09654f787793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-sde-selanjutnya']/span</value>
      <webElementGuid>f8c21f97-9674-41b8-8c07-47afee561866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rupiah'])[11]/following::span[1]</value>
      <webElementGuid>ca320d61-11ad-4478-a9a1-f2636be8ae35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sewa Modal Per Bulan'])[2]/following::span[1]</value>
      <webElementGuid>b1ba76e2-5afb-4b97-8e94-404c9f24918a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. Pegadaian'])[1]/preceding::span[3]</value>
      <webElementGuid>b35279cc-1ea9-47f7-9700-1d1e399e24a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kesalahan'])[1]/preceding::span[3]</value>
      <webElementGuid>ee2a0fc9-59ff-4882-89ea-5b88e1262073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/span</value>
      <webElementGuid>97dbf353-e85c-4a53-a1c9-a53a46128e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' SELANJUTNYA ' or . = ' SELANJUTNYA ')]</value>
      <webElementGuid>8677b03f-cb41-416b-b601-374db5941283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
